### PR TITLE
Added step that patches missing requirement in requirements.txt

### PR DESCRIPTION
**Pull request by Bystroushaak**
I've found missing requirement in some github repository and fixed version seems to be working.

### CODE REVIEW

**Comment by Bystroushaak** [comment]
Okay, now I am slightly confused. Is there any relation to https://github.com/pebble-dev/RebbleOS ? Should I send commits / patches here or to the other repository?

**Comment by jwise** [comment]
Yeah, I think https://github.com/pebble-dev/RebbleOS is the way to go.

**Comment by Bystroushaak** [comment]
Okay, so are there any reasons why https://rebble.io/projects/ points to this repo? I mean I am still trying to understand. The "official" repository linked above looks kinda dead.

**Comment by ginge** [comment]
We have migrated to https://rebble.io/projects/. It all started in this repo, but is no longer considered the canonical master repository.
If you would be so kind as to PR against  https://rebble.io/projects/ (if you didn't already) it would be appreciated

**Comment by ginge** [comment]
> Okay, so are there any reasons why https://rebble.io/projects/ points to this repo? Legacy. It needs updating. Thanks for noticing!

**Comment by Bystroushaak** [comment]
I'll send PR tomorrow, its kinda late here (00:21). Thanks for the clarification, I'll definitely use the other repository. Maybe it would make sense to change the README in this repo to point to the official one.

**Pull request closed without merging**
